### ISSUE TITLE
License information in github repo too?

### ISSUE THREAD

**Issue by LibrErli** [vt-digital-libraries-platform/NOID-mint#4]
Hi, thanks for your noid generator! I have successfully reused your script here. One question the script is published on pypi under MIT License, what it be possible to add this license information in the github repo too? it makes the reuseabillity of the script more clear. 

Thanks in advance!
Christian Erlinger

**Comment by yinlinchen** [comment]
Added https://github.com/vt-digital-libraries-platform/NOID-mint/commit/65bd59aada7a13aa20cde11bc093be9c82e08641
